### ISSUE TITLE
Bug while saving "illegal value for line"

### ISSUE THREAD

**Issue by Bartheleway** [celador/ForceCode#181]
**Describe the bug**
Hi, I'm still having an issue with that "illegal value for line", this time SF is giving me the following error : This schedulable class has jobs pending or in progress

**Expected behavior**
Get the real error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 3.9.7

**Additional context**
We can safely deploy using the "choose files" from the "deploy package" menu option.
It seems that compile/deploy is not an exact equivalent because it can't override scheduled classes.

**Comment by daishi4u** [comment]
This will be fixed in the next release (3.9.8). As far as the difference between the compile and deploy options, compile is just like if you were to save the file in the dev console, whereas deploying is the equivalent to using a change set (When it comes to code). Change sets allow you to push new versions of scheduled classes as well.

Anyways, thanks for reporting the issue!

**Comment by daishi4u** [comment]
This is now fixed in v3.9.9

**Comment by RandallFlagg** [comment]
@daishi4u I just got this when using version 3.14.1. This is happening to me because the code I am using is using a piece from another file that wasn't updated on the ORG.

**Comment by daishi4u** [comment]
@RandallFlagg I will be uploading version 3.15.0-1 in the slack beta-testing channel in a little bit. If you could possibly test this version and let me know if it fixes the issue then I would appreciate it. Thanks!

**Comment by RandallFlagg** [comment]
Will try to reproduce and test it as soon as I can

**Comment by RandallFlagg** [comment]
@daishi4u Just tested it with 3.15.0-2 and the problem still exists. Tell me if you need anything else from me.

**Comment by daishi4u** [comment]
@RandallFlagg can you give me a short code example? Are you just calling another class' method?
